variables:
  GIT_DEPTH: 1
  GOPROXY: "https://goproxy.cn,direct"

cache:
  key: "blog-go"
  paths:
    - ./vendor

stages:
  - build
  - make

build_binary:
  image: golang:alpine
  stage: build
  before_script:
    - cp -R ./vendor $GOPATH 2>/dev/null
  script:
    - CGO_ENABLED=0 go build app.go
  after_script:
    - go mod vendor
  artifacts:
    when: on_success
    paths:
      - ./app

make_image:
  cache: {}
  image: docker:stable
  stage: make
  script:
    - sed -i "s/blog:\w\+-BE/blog:$CI_COMMIT_SHORT_SHA-BE/g" docker-compose.yml
    - docker login -u="$DOCKER_USERNAME_ALI" -p="$DOCKER_PASSWORD_ALI" $DOCKER_REPOSITORY_ALI
    - docker build
        --build-arg ALI_AK=$ALI_AK
        --build-arg ALI_SK=$ALI_SK
        --build-arg ALI_ENDPOINT=$ALI_ENDPOINT
        --build-arg ALI_BUCKET=$ALI_BUCKET
        -t $DOCKER_REPOSITORY_ALI/calabash/blog:$CI_COMMIT_SHORT_SHA-BE
        -f ./Dockerfile .
    - docker push $DOCKER_REPOSITORY_ALI/calabash/blog:$CI_COMMIT_SHORT_SHA-BE
    - scp -P $SSH_PORT ./docker-compose.yml deploy-server:~/deploy/blog/be
    - ssh deploy-server -p $SSH_PORT "cd ~/deploy/blog/be && docker-compose up -d"





