variables:
  GIT_DEPTH: 1
  GOPROXY: "https://goproxy.cn,direct"

cache:
  key: "binary"
  untracked: true
  paths:
    - ./

stages:
  - build
  - make

build_binary:
  image: golang:alpine
  stage: build
  script:
    - CGO_ENABLED=0 go build app.go

make_image:
  image: docker:stable
  stage: make
  script:
    - sed -i "s/blog:\w\+-BE/blog:$CI_COMMIT_SHORT_SHA-BE/g" docker-compose.yml
    - docker login -u="$DOCKER_USERNAME_ALI" -p="$DOCKER_PASSWORD_ALI" $DOCKER_REPOSITORY_ALI
    - docker build
        --build-arg ALI_AK=$ALI_AK
        --build-arg ALI_SK=$ALI_SK
        --build-arg ALI_ENDPOINT=$ALI_ENDPOINT
        --build-arg ALI_BUCKET=$ALI_BUCKET
        --build-arg REDIS_MASTER_URL=$REDIS_MASTER_URL
        --build-arg REDIS_SLAVE1_URL=$REDIS_SLAVE1_URL
        --build-arg REDIS_SLAVE2_URL=$REDIS_SLAVE2_URL
        -t $DOCKER_REPOSITORY_ALI/calabash/blog:$CI_COMMIT_SHORT_SHA-BE
        -f ./Dockerfile .
    - docker push $DOCKER_REPOSITORY_ALI/calabash/blog:$CI_COMMIT_SHORT_SHA-BE
    - scp ./docker-compose.yml deploy-server:~/deploy/blog/be
    - ssh deploy-server "cd ~/deploy/blog/be && docker-compose up -d"





