version: "3"
services:
  go_backend:
    build:
      context: .
      args:
        GOPROXY: "https://goproxy.cn,direct"
    environment:
      ALI_AK: ${ALI_AK}
      ALI_SK: ${ALI_SK}
      ALI_BUCKET: ${ALI_BUCKET}
      ALI_ENDPOINT: ${ALI_ENDPOINT}
    container_name: "go-backend"
    ports:
      - 3000:8080
    network_mode: bridge
    restart: unless-stopped
    extra_hosts:
      - "dockerhost:172.18.0.1"
    command: ["./app"]
