FROM alpine
LABEL maintainer=Caaalabash
WORKDIR /app
ARG ALI_ENDPOINT
ARG ALI_BUCKET
ARG ALI_AK
ARG ALI_SK
ARG REDIS_MASTER_URL
ARG REDIS_SLAVE1_URL
ARG REDIS_SLAVE2_URL
ENV ALI_ENDPOINT $ALI_ENDPOINT
ENV ALI_BUCKET $ALI_BUCKET
ENV ALI_SK $ALI_SK
ENV ALI_AK $ALI_AK
ENV REDIS_MASTER_URL $REDIS_MASTER_URL
ENV REDIS_SLAVE1_URL $REDIS_SLAVE1_URL
ENV REDIS_SLAVE2_URL $REDIS_SLAVE2_URL
COPY ./ /app
