version: "3"
services:
  go_backend:
    build: .
    container_name: "go-backend"
    ports:
      - 3000:8080
    network_mode: bridge
    restart: unless-stopped
    extra_hosts:
      - "dockerhost:172.18.0.1"
    command: ["./app"]
