FROM alpine
LABEL maintainer=Caaalabash
WORKDIR /app
ARG ALI_ENDPOINT
ARG ALI_BUCKET
ARG ALI_AK
ARG ALI_SK
ENV ALI_ENDPOINT $ALI_ENDPOINT
ENV ALI_BUCKET $ALI_BUCKET
ENV ALI_SK $ALI_SK
ENV ALI_AK $ALI_AK
COPY ./ /app
